//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SqlRanger.StoredProcedures;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Xml;


namespace StoredProcedures {
    
}
